Tweaks:
  # Minimum ticks of interval between growing
  cooldownTicks: 5
  # Grow saplings when player sneaks
  growSaplings: true
  # Grow crops when player sneaks
  growCrops: true
  # Grow crops that are unaffected by bone meal when player sneaks (Sugar Cane, Cactus, Nether Wart, Chorus Flower)
  growExtraCrops: true
  # Show bonemeal particles when appropriate. Not sure why you would turn this off, but eh
  showParticles: true
  # Play sound of using bone meal
  playSound: true
  # Radius of blocks to check for saplings and crops
  blockRadius: 5
  # Radius of mobs to check for saplings and crops
  mobRadius: 5
  # Percentage of blocks to check for saplings and crops
  blockPercentage: 0.1
  # Percentage of mobs to check for saplings and crops
  mobPercentage: 0.05
  # Random ticks that apply to crops that are unaffected by bone meal
  extraRandomTicks: 8
